### ISSUE TITLE
Create React App is deprecated

### ISSUE THREAD

**Issue by hnucamendi** [michael-ortiz/LinkifyBio#1]
noticed you used Create React app(CRA), and wanted to point out that CRA was deprecated in 2023 due to it being incompatible with new tooling & slow as it relied on webpack. 

Here are some articles on the matter:
1. https://dev.to/ag2byte/create-react-app-is-officially-dead-h7o
2. https://www.theodinproject.com/lessons/node-path-react-new-setting-up-a-react-environment
3. https://dev.to/clumsycoder/is-create-react-app-really-dead-what-are-other-options-1j39

The recommendation I have seen most popular is [Vite](https://vitejs.dev/), I have personally used vite, and it is super similar to CRA + it comes with some really nice features out of the box like [env vars and modes](https://vitejs.dev/guide/env-and-mode.html).

That being said, you might also be interested in [Svelte](https://svelte.dev/). I dont know much about Svelte but I have heard its the leading tech in web apps. Of course you dont want to just join the hypetrain, but something to consider.

I dont mind helping out with a migration from CRA to Vite or some other tooling for React and or Svelte, but just wanted to let you know!

**Comment by michael-ortiz** [comment]
Oh wow! I was not aware of this. I will look into it more. Does this bring performance improvements to the app?

**Comment by hnucamendi** [comment]
Yea it should improve load times to the final build because CRA creates larger JavaScript bundles than Vite. But that is about as much as I know, since I dont spend too much time in React

**Comment by hnucamendi** [comment]
> Oh wow! I was not aware of this. I will look into it more. Does this bring performance improvements to the app?

Yea it should improve load times to the final build because CRA creates larger JavaScript bundles than Vite. But that is about as much as I know, since I dont spend too much time in React
