### ISSUE TITLE
Update Lambda API Node Version

### ISSUE THREAD

**Issue by hnucamendi** [michael-ortiz/LinkifyBio#9]
Currently the version of the API Lambda is node 16 [here](https://github.com/michael-ortiz/LinkifyBio/blob/main/terraform/lambda.tf#L4). Goal of this issue is to update it to the latest LTS version - currently Node 20 as of 04/19/2024

**Comment by michael-ortiz** [comment]
Thank for this. We upgraded the lambda to Node 20.
